EQUALS
  SATNUM  4    8  10    8   8  1 37 /  
  SATNUM  4    9   9    7   7  1 37 /  
  SATNUM  4    8  10    7   7  1 37 /  
  
  SATNUM  4    5   7   18  18  1 37 / 
  SATNUM  4    6   6   17  19  1 37 /  
  
  SATNUM  4    9  11   14  16  1 37 / 
  
  SATNUM  4    7   7    3   3  1 37 /  
  
  SATNUM  4   10  12    6   6  1 37 /  
  SATNUM  4   11  11    5   7  1 37 /  
  
  SATNUM  4   10  12   11  11  1 37 / 
  SATNUM  4   11  11   10  12  1 37 /  
  
  SATNUM  4    5   7   12  12  1 37 / 
  SATNUM  4    6   6   11  13  1 37 / 
  
  SATNUM  4    1   5   10  10  1 37 /  
  SATNUM  4    3   3    8  12  1 37 /  
  SATNUM  4    2   4    9  11  1 37 /  
  
  SATNUM  4    4   6   16  19  1 37 /  
  
  SATNUM  4    5   5   16  16  1 37 / 
/